# Generated by Django 5.0.6 on 2024-05-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_ext',
            new_name='answer_text',
        ),
    ]
